values:
  - number: 2
    pos_x: 6
    pos_y: 0

  - number: 8
    pos_x: 1
    pos_y: 1

  - number: 7
    pos_x: 5
    pos_y: 1

  - number: 9
    pos_x: 7
    pos_y: 1

  - number: 6
    pos_x: 0
    pos_y: 2

  - number: 2
    pos_x: 2
    pos_y: 2  
    
  - number: 5
    pos_x: 6
    pos_y: 2

  - number: 7
    pos_x: 1
    pos_y: 3

  - number: 6
    pos_x: 4
    pos_y: 3

  - number: 9
    pos_x: 3
    pos_y: 4

  - number: 1
    pos_x: 5
    pos_y: 4

  - number: 2
    pos_x: 4
    pos_y: 5

  - number: 4
    pos_x: 7
    pos_y: 5

  - number: 5
    pos_x: 2
    pos_y: 6

  - number: 6
    pos_x: 6
    pos_y: 6

  - number: 3
    pos_x: 8
    pos_y: 6

  - number: 9
    pos_x: 1
    pos_y: 7

  - number: 4
    pos_x: 3
    pos_y: 7

  - number: 7
    pos_x: 7
    pos_y: 7

  - number: 6
    pos_x: 2
    pos_y: 8